apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boltztrader-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - boltztrader.com
        - www.boltztrader.com
      secretName: boltztrader-tls
  rules:
    - host: boltztrader.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: boltztrader-service
                port:
                  number: 80
    - host: www.boltztrader.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: boltztrader-service
                port:
                  number: 80